### ISSUE TITLE
Feature Request: Vite plugin

### ISSUE THREAD

**Issue by lucas-teks** [runreflect/webpack-react-component-name#34]
Hello, that's a super cool feature, but is a Vite plugin under development / in the roadmap?
I'd see most of your customers aligned to modern tech such as Vite bundler.

**Comment by tmcneal** [comment]
Hi Lucas,

There are no plans to port this to Vite or any other Webpack alternative. The latest generation of bundlers have less extensible plugin frameworks, so it may not even be possible to port this to Vite et al...
