### ISSUE TITLE
Usage w/ next.js

### ISSUE THREAD

**Issue by chrisvariety** [runreflect/webpack-react-component-name#6]
Hello!

I'm trying to use this with a next.js production build, but running into issues with the minification process stripping `displayName`.

Here's a sandbox you can check out, which is just a basic empty next.js application: https://codesandbox.io/s/stupefied-sunset-un5gs

I've added the following to `next.config.js`:

```js
const WebpackReactComponentNamePlugin = require("webpack-react-component-name");

module.exports = {
  webpack: (config) => {
    config.plugins.push(new WebpackReactComponentNamePlugin());

    return config;
  }
};
```

I've also changed the `dev` script in `package.json` to `next build && next start` to simulate a production build in the codesandbox environment. As you'll see, everything is reduced to one character, I believe thanks to `terser` automatically running on production builds. Is there a way to avoid this, or would the recommendation be to use this plugin for development builds only? Thanks !

**Comment by tmcneal** [comment]
Thank you for reporting this, and for the clear repro steps!  I'm looking into this now.

**Comment by elepedus** [comment]
Any luck getting to the bottom of this? I am also experiencing the same issue.  Not sure if relevant, but when using this with NextJS 10.x, this only works with webpack 5, and outputs a load of warnings of the form:
```
[webpack.cache.PackFileCacheStrategy] Skipped not serializable cache item 'Compilation/modules|/<project_path>/node_modules/next/dist/build/webpack/loaders/next-babel-loader.js??ruleSet[1].rules[1].use!/<project_path>/src/pages/_error.tsx': No serializer registered for ModuleAppenderDependency
<w> while serializing webpack/lib/cache/PackFileCacheStrategy.PackContentItems -> webpack/lib/NormalModule -> Array { 37 items } -> ModuleAppenderDependency

```

Trying to use it with webpack 4 crashes with `Error: Dependency.getReference was removed in favor of Dependency.getReferencedExports, ModuleGraph.getModule and ModuleGraph.getConnection().active`

**Comment by tmcneal** [comment]
Apologies for the late follow-up here. We've released support for Webpack 5 but I'm seeing that we're still not generating `displayName` properties for next.js apps. I don't know much about next.js, but it must be changing the AST such that the plugin isn't able to find the React components.

I'll keep this open to track supporting next.js in a future release.
